services:
  # Single container with Next.js + n8n + LaTeX + SQLite
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lets-get-a-job-all-in-one
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5678:5678"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_N8N_JD_WEBHOOK_URL=http://localhost:5678/webhook/process-jd
      - NEXT_PUBLIC_N8N_RESUME_WEBHOOK_URL=http://localhost:5678/webhook/process-resume
      - NEXT_PUBLIC_N8N_COVER_LETTER_WEBHOOK_URL=http://localhost:5678/webhook/process-cover-letter
      - NEXT_PUBLIC_N8N_EVALUATION_WEBHOOK_URL=http://localhost:5678/webhook/evaluate-ats
      - NEXT_PUBLIC_N8N_TIMEOUT=120000
      - NEXT_PUBLIC_DEBUG_N8N=false
    volumes:
      - app_data:/app/data
      - n8n_data:/app/n8n-data
    healthcheck:
      test: [ "CMD", "sh", "-c", "wget --spider -q http://localhost:3000/api/health && wget --spider -q http://localhost:5678/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  app_data:
    driver: local
  n8n_data:
    driver: local
